

import Foundation



// Eventually make it able to be dynamically changed
let schoolData = [
    School(name: "Affton", isFavorite: true, location: "Affton", yearFounded: "1930", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "AHS", index: 0),
    School(name: "Althoff Catholic", isFavorite: true, location: "Althoff", yearFounded: "1964", state: "IL", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "ACHS", index: 1),
    School(name: "Alton", location: "Alton", yearFounded: "1902", state: "IL", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "AHS", index: 2),
    School(name: "Alton Marquette", location: "Alton", yearFounded: "1927", state: "IL", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "AMHS", index: 3),
    School(name: "Barat", location: "Chesterfield", yearFounded: "2007", state: "MO", isClosed: true, schoolSuffix: SchoolSuffix.academy, schoolAbbr: "BA", index: 4),
    School(name: "Bayless", location: "St. Louis", yearFounded: "1868", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "BHS", index: 5),
    School(name: "Belleville East", location: "Belleville", yearFounded: "1966", state: "IL", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "BEHS", index: 6),
    School(name: "Belleville West", location: "Belleville", yearFounded: "1916", state: "IL", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "BWHS", index: 7),
    School(name: "Borgia", location: "Washington", yearFounded: "1901", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "SFB", index: 8),
    School(name: "Breese Central", location: "Breese", yearFounded: "1971", state: "IL", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "BCHS", index: 9),
    School(name: "Brentwood", location: "Brentwood", yearFounded: "1927", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "BHS", index: 10),
    School(name: "Cahokia", location: "Cahokia Heights", yearFounded: "1952", state: "IL", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "CHS", index: 11),
    School(name: "Cardinal Ritter", location: "St. Louis", yearFounded: "1979", state: "MO", schoolSuffix: SchoolSuffix.collegePreparatory, schoolAbbr: "CRCP", index: 12),
    School(name: "Carlyle", location: "Carlyle", yearFounded: "", state: "IL", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "CHS", index: 13),
    School(name: "Carnahan", location: "St. Louis", yearFounded: "2006", state: "MO", isClosed: true, schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "CHS", index: 14),
    School(name: "CBC", location: "St. Louis", yearFounded: "1850", state: "MO", schoolSuffix: SchoolSuffix.none, schoolAbbr: "CBC", index: 15),
    School(name: "Chaminade", location: "Frontenac", yearFounded: "1910", state: "MO", schoolSuffix: SchoolSuffix.collegePreparatory, schoolAbbr: "CCP", index: 16),
    School(name: "Civic Memorial", location: "Bethalto", yearFounded: "1951", state: "IL", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "CMHS", index: 17),
    School(name: "Clayton", location: "Clayton", yearFounded: "1908", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "CHS", index: 18),
    School(name: "Cleveland", location: "St. Louis", yearFounded: "1915", state: "MO", isClosed: true, schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "CHS", index: 19),
    School(name: "Collinsville", location: "Collinsville", yearFounded: "1908", state: "IL", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "CHS", index: 20),
    School(name: "Columbia", location: "Columbia", yearFounded: "1876", state: "IL", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "CHS", index: 21),
    School(name: "Cor Jesu", location: "St. Louis", yearFounded: "1956", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "CJ", index: 22),
    School(name: "Crossroads", location: "St. Louis", yearFounded: "1974", state: "MO", schoolSuffix: SchoolSuffix.collegePreparatory, schoolAbbr: "CP", index: 23),
    School(name: "Crystal City", location: "Crystal City", yearFounded: "", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "CCHS", index: 24),
    School(name: "De Soto", location: "De Soto", yearFounded: "1882", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "DSHS", index: 25),
    School(name: "De Smet", location: "Creve Coeur", yearFounded: "1967", state: "MO", schoolSuffix: SchoolSuffix.jesuit, schoolAbbr: "DS", index: 26),
    School(name: "DuBourg", location: "St. Louis", yearFounded: "1950", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "BD", index: 27),
    School(name: "Duchesne", location: "St. Charles", yearFounded: "1956", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "DHS", index: 28),
    School(name: "Dupo", location: "Dupo", yearFounded: "", state: "IL", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "DHS", index: 29),
    School(name: "East St. Louis", location: "East St. Louis", yearFounded: "1865", state: "IL", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "ESL", index: 30),
    School(name: "Edwardsville", location: "Edwardsville", yearFounded: "1910", state: "IL", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "EHS", index: 31),
    School(name: "Eureka", location: "Eureka", yearFounded: "1908", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "EHS", index: 32),
    School(name: "Festus", location: "Festus", yearFounded: "1901", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "FHS", index: 33),
    School(name: "Fort Zumwalt East", location: "St. Peters", yearFounded: "2007", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "FZE", index: 34),
    School(name: "Fort Zumwalt North", location: "O'Fallon", yearFounded: "1960", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "FZN", index: 35),
    School(name: "Fort Zumwalt South", location: "O'Fallon", yearFounded: "1987", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "FZS", index: 36),
    School(name: "Fort Zumwalt West", location: "O'Fallon", yearFounded: "1998", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "FZW", index: 37),
    School(name: "Fox", location: "Arnold", yearFounded: "1955", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "FHS", index: 38),
    School(name: "Francis Howell", location: "St. Charles", yearFounded: "1881", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "FHHS", index: 39),
    School(name: "Francis Howell Central", location: "Cottleville", yearFounded: "1997", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "FHC", index: 40),
    School(name: "Francis Howell North", location: "St. Charles", yearFounded: "1983", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "FHN", index: 41),
    School(name: "Freeburg", location: "Freeburg", yearFounded: "1904", state: "IL", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "FHS", index: 42),
    School(name: "Gateway STEM", location: "St. Louis", yearFounded: "2012", state: "MO", schoolSuffix: SchoolSuffix.none, schoolAbbr: "STEM", index: 43),
    School(name: "Gibault", location: "Waterloo", yearFounded: "1966", state: "IL", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "GHS", index: 44),
    School(name: "Gillespie", location: "Gillespie", yearFounded: "", state: "IL", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "GHS", index: 45),
    School(name: "Grandview", location: "Grandview", yearFounded: "1980", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "GHS", index: 46),
    School(name: "Greenville IL", location: "Greenville", yearFounded: "1869", state: "IL", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "GHS", index: 47),
    School(name: "Hancock", location: "St. Louis", yearFounded: "1926", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "HHS", index: 48),
    School(name: "Hazelwood East", location: "St. Louis", yearFounded: "1974", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "HEHS", index: 49),
    School(name: "Hazelwood West", location: "St. Louis", yearFounded: "1974", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "HWHS", index: 50),
    School(name: "Hazelwood Central", location: "Florissant", yearFounded: "1954", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "HCHS", index: 51),
    School(name: "Herculaneum", location: "Herculaneum", yearFounded: "1915", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "HHS", index: 52),
    School(name: "Hermann", location: "Hermann", yearFounded: "2000", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "HHS", index: 53),
    School(name: "Highland IL", location: "Highland", yearFounded: "1894", state: "IL", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "HHS", index: 54),
    School(name: "Hillsboro MO", location: "Hillsboro", yearFounded: "~1924", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "HHS", index: 55),
    School(name: "Holt", location: "Wentzville", yearFounded: "1896", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "HHS", index: 56),
    School(name: "Incarnate Word", location: "Normandy", yearFounded: "1932", state: "MO", schoolSuffix: SchoolSuffix.academy, schoolAbbr: "IWA", index: 57),
    School(name: "Jennings", location: "Jennings", yearFounded: "1871", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "JHS", index: 58),
    School(name: "Jerseyville", location: "Jerseyville", yearFounded: "1874", state: "IL", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "JHS", index: 59),
    School(name: "Jefferson", location: "Conception Junction", yearFounded: "", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "JHS", index: 60),
    School(name: "John Burroughs", location: "St. Louis", yearFounded: "1923", state: "MO", schoolSuffix: SchoolSuffix.school, schoolAbbr: "JBS", index: 61),
    School(name: "Kennedy", location: "Manchester", yearFounded: "1968", state: "MO", isClosed: true, schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "KHS", index: 62),
    School(name: "Kirkwood", location: "Kirkwood", yearFounded: "1896", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "KHS", index: 63),
    School(name: "Ladue", location: "Ladue", yearFounded: "1952", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "LHS", index: 64),
    School(name: "Lafayette", location: "Wildwood", yearFounded: "1960", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "LHS", index: 65),
    School(name: "Lebanon IL", location: "Lebanon", yearFounded: "", state: "IL", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "LHS", index: 66),
    School(name: "Liberty", location: "Lake St. Louis", yearFounded: "2013", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "LHS", index: 67),
    School(name: "Lindbergh", location: "St. Louis", yearFounded: "1951", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "LHS", index: 68),
    School(name: "Lovejoy", location: "Brooklyn", yearFounded: "", state: "IL", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "LHS", index: 69),
    School(name: "Lutheran North", location: "St. Louis", yearFounded: "1964", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "LNHS", index: 70),
    School(name: "Lutheran St. Charles", location: "St. Peters", yearFounded: "1982", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "LHS", index: 71),
    School(name: "Lutheran South", location: "St. Louis", yearFounded: "1957", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "LSHS", index: 72),
    School(name: "Madison IL", location: "Madison", yearFounded: "1903", state: "IL", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "MHS", index: 73),
    School(name: "Maplewood-RH", location: "Maplewood", yearFounded: "1929", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "MRHS", index: 74),
    School(name: "Marissa", location: "Marissa", yearFounded: "1900", state: "IL", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "MHS", index: 75),
    School(name: "Marquette", location: "Chesterfield", yearFounded: "1993", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "MHS", index: 76),
    School(name: "Mascoutah", location: "Mascoutah", yearFounded: "1952", state: "IL", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "MHS", index: 77),
    School(name: "Mater Dei", location: "Breese", yearFounded: "1954", state: "IL", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "MDHS", index: 78),
    School(name: "McCluer", location: "Florissant", yearFounded: "1957", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "MHS", index: 79),
    School(name: "McCluer North", location: "Florissant", yearFounded: "1971", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "MNHS", index: 80),
    School(name: "McCluer South Berkeley STEAM", location: "Ferguson", yearFounded: "2004", state: "MO", schoolSuffix: SchoolSuffix.none, schoolAbbr: "STEAM", index: 81),
    School(name: "Mehlville", location: "Mehlville", yearFounded: "1925", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "MHS", index: 82),
    School(name: "Metro East Lutheran", location: "Edwardsville", yearFounded: "1977", state: "IL", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "MEL", index: 83),
    School(name: "MICDS", location: "St. Louis", yearFounded: "1859", state: "MO", schoolSuffix: SchoolSuffix.none, schoolAbbr: "MICDS", index: 84),
    School(name: "Miller Career", location: "St. Louis", yearFounded: "", state: "MO", schoolSuffix: SchoolSuffix.academy, schoolAbbr: "MCA", index: 85),
    School(name: "Nashville", location: "Nashville", yearFounded: "1954", state: "IL", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "NHS", index: 86),
    School(name: "Nerinx Hall", location: "Webster Groves", yearFounded: "1924", state: "MO", schoolSuffix: SchoolSuffix.academy, schoolAbbr: "NHA", index: 87),
    School(name: "New Haven", location: "New Haven", yearFounded: "1903", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "NH", index: 88),
    School(name: "Normandy", location: "St. Louis", yearFounded: "1923", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "NOR", index: 89),
    School(name: "North Tech", location: "St. Louis", yearFounded: "", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "NT", index: 90),
    School(name: "Northwest", location: "St. Louis", yearFounded: "1964", state: "MO", isClosed: true, schoolSuffix: SchoolSuffix.academy, schoolAbbr: "NWA", index: 91),
    School(name: "Northwest Cedar Hill", location: "Cedar Hill", yearFounded: "1955", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "NWCH", index: 92),
    School(name: "Notre Dame", location: "St. Louis", yearFounded: "1934", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "ND", index: 93),
    School(name: "O'Fallon Township", location: "O'Fallon", yearFounded: "1901", state: "IL", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "OFT", index: 94),
    School(name: "Oakville", location: "Oakville", yearFounded: "1970", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "OAK", index: 95),
    School(name: "Okawville", location: "Okawviille", yearFounded: "", state: "IL", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "OKA", index: 96),
    School(name: "Orchard Farm", location: "St. Charles", yearFounded: "1959", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "OF", index: 97),
    School(name: "Owensville", location: "Owensville", yearFounded: "", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "OWEN", index: 98),
    School(name: "Pacific", location: "Pacific", yearFounded: "", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "PAC", index: 99),
    School(name: "Parkway Central", location: "Chesterfield", yearFounded: "1954", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "PCH", index: 100),
    School(name: "Parkway North", location: "St. Louis", yearFounded: "1971", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "PNH", index: 101),
    School(name: "Parkway South", location: "Manchester", yearFounded: "1976", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "PSH", index: 102),
    School(name: "Parkway West", location: "Ballwin", yearFounded: "1968", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "PWH", index: 103),
    School(name: "Pattonville", location: "Maryland Heights", yearFounded: "1933", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "PAT", index: 104),
    School(name: "Perryville", location: "Perryville", yearFounded: "1865", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "PVH", index: 105),
    School(name: "Piasa Southwestern", location: "Piasa", yearFounded: "", state: "IL", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "PSW", index: 106),
    School(name: "Principia", location: "Town and Country", yearFounded: "1898", state: "MO", schoolSuffix: SchoolSuffix.school, schoolAbbr: "PRIN", index: 107),
    School(name: "Priory", location: "St. Louis", yearFounded: "1956", state: "MO", schoolSuffix: SchoolSuffix.school, schoolAbbr: "PRI", index: 108),
    School(name: "Red Bud", location: "Red Bud", yearFounded: "", state: "IL", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "RBH", index: 109),
    School(name: "Ritenour", location: "St. Louis", yearFounded: "1911", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "RIT", index: 110),
    School(name: "Riverview Gardens", location: "St. Louis", yearFounded: "", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "RVG", index: 111),
    School(name: "Roosevelt", location: "St. Louis", yearFounded: "1925", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "ROOS", index: 112),
    School(name: "Rosati-Kain", location: "St. Louis", yearFounded: "1911", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "RK", index: 113),
    School(name: "Roxana", location: "Roxana", yearFounded: "1941", state: "IL", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "ROX", index: 114),
    School(name: "Seckman", location: "Imperial", yearFounded: "1997", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "SEC", index: 115),
    School(name: "SLUH", location: "St. Louis", yearFounded: "1818", state: "MO", schoolSuffix: SchoolSuffix.none, schoolAbbr: "SLUH", index: 116),
    School(name: "Soldan", location: "St. Louis", yearFounded: "1909", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "SOL", index: 117),
    School(name: "St. Charles", location: "St. Charles", yearFounded: "1899", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "SCHS", index: 118),
    School(name: "St. Charles West", location: "St. Charles", yearFounded: "1976", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "SCW", index: 119),
    School(name: "St. Clair", location: "St. Clair", yearFounded: "", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "SCL", index: 120),
    School(name: "St. Dominic", location: "O'Fallon", yearFounded: "1962", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "SDO", index: 121),
    School(name: "St. James", location: "St. James", yearFounded: "1940", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "SJH", index: 122),
    School(name: "St. Joseph's ", location: "St. Louis", yearFounded: "1840", state: "MO", schoolSuffix: SchoolSuffix.academy, schoolAbbr: "SJA", index: 123),
    School(name: "St. Mary's", location: "St. Louis", yearFounded: "1931", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "SMH", index: 124),
    School(name: "St. Pius X", location: "Crystal City", yearFounded: "1959", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "SPX", index: 125),
    School(name: "St. Vincent", location: "Perryville", yearFounded: "1896", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "SVH", index: 126),
    School(name: "Staunton", location: "Staunton", yearFounded: "", state: "IL", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "STA", index: 127),
    School(name: "Steelville", location: "Steelville", yearFounded: "1886", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "STE", index: 128),
    School(name: "Sullivan", location: "Sullivan", yearFounded: "1883", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "SUL", index: 129),
    School(name: "Summit", location: "Fenton", yearFounded: "1993", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "SUM", index: 130),
    School(name: "Sumner", location: "St. Louis", yearFounded: "1875", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "SUMN", index: 131),
    School(name: "Timberland", location: "Wentzville", yearFounded: "2002", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "TMB", index: 132),
    School(name: "Triad", location: "Troy", yearFounded: "1999", state: "IL", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "TRI", index: 133),
    School(name: "Trinity Catholic", location: "St. Louis", yearFounded: "2003", state: "MO", isClosed: true, schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "TRN", index: 134),
    School(name: "Troy Buchanan", location: "Troy", yearFounded: "1914", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "TBH", index: 135),
    School(name: "Union", location: "Union", yearFounded: "1835", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "UNH", index: 136),
    School(name: "University City", location: "University City", yearFounded: "1930", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "UCITY", index: 137),
    School(name: "Ursuline", location: "St. Louis", yearFounded: "1848", state: "MO", schoolSuffix: SchoolSuffix.academy, schoolAbbr: "URS", index: 138),
    School(name: "Valley Park", location: "Valley Park", yearFounded: "1932", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "VP", index: 139),
    School(name: "Valmeyer", location: "Valmeyer", yearFounded: "", state: "IL", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "VAL", index: 140),
    School(name: "Vashon", location: "St. Louis", yearFounded: "1927", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "VSH", index: 141),
    School(name: "Veritas Christian", location: "O'fallon", yearFounded: "1980", state: "MO", schoolSuffix: SchoolSuffix.academy, schoolAbbr: "VCA", index: 142),
    School(name: "Vianney", location: "St. Louis", yearFounded: "1960", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "VIA", index: 143),
    School(name: "Villa Duchesne", location: "St. Louis", yearFounded: "1929", state: "MO", schoolSuffix: SchoolSuffix.none, schoolAbbr: "VD", index: 144),
    School(name: "Visitation", location: "St. Louis", yearFounded: "1833", state: "MO", schoolSuffix: SchoolSuffix.academy, schoolAbbr: "VIS", index: 145),
    School(name: "Warrenton", location: "Warrenton", yearFounded: "1906", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "WAR", index: 146),
    School(name: "Washington", location: "Washington", yearFounded: "1900", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "WASH", index: 147),
    School(name: "Waterloo", location: "Waterloo", yearFounded: "1895", state: "IL", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "WAT", index: 148),
    School(name: "Webster Groves", location: "Webster Groves", yearFounded: "1889", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "WEB", index: 149),
    School(name: "Wesclin", location: "Trenton", yearFounded: "2014", state: "IL", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "WES", index: 150),
    School(name: "Westminster Christian", location: "Town and Country", yearFounded: "1976", state: "MO", schoolSuffix: SchoolSuffix.academy, schoolAbbr: "WESM", index: 151),
    School(name: "Whitfield", location: "St. Louis", yearFounded: "1952", state: "MO", schoolSuffix: SchoolSuffix.school, schoolAbbr: "WHIT", index: 152),
    School(name: "Windsor", location: "Imperial", yearFounded: "1922", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "WIN", index: 153),
    School(name: "Winfield", location: "Winfield", yearFounded: "", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "WINF", index: 154),
    School(name: "Wood River", location: "Wood River", yearFounded: "1919", state: "IL", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "WRH", index: 155),
    School(name: "Wright City", location: "Wright City", yearFounded: "1922", state: "MO", schoolSuffix: SchoolSuffix.highSchool, schoolAbbr: "WC", index: 156),

]
